"""Print the Supabase SQL needed for this app."""

from __future__ import annotations

EXERCISES_SQL = """
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null unique,
  profile_data jsonb not null default '{}'::jsonb,
  scraped_at timestamptz not null default now()
);
""".strip()


def main() -> None:
    print(EXERCISES_SQL)


if __name__ == "__main__":
    main()
