"""Print the Supabase SQL needed for this app."""

from __future__ import annotations

try:
    from .full_schema import load_ai_schema_sql, load_full_schema_sql
except ImportError:
    from full_schema import load_ai_schema_sql, load_full_schema_sql

PROFILE_FIELDS = (
    "force",
    "category",
    "mechanic",
    "equipment",
    "difficulty",
    "primary_muscle",
    "secondary_muscles",
    "variations_available",
)
INTEGER_PROFILE_FIELDS = {"secondary_muscles", "variations_available"}
EXERCISE_COLUMNS = ("id", "name", "url", *PROFILE_FIELDS, "scraped_at")

EXERCISES_SQL = """
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null unique,
  force text,
  category text,
  mechanic text,
  equipment text,
  difficulty text,
  primary_muscle text,
  secondary_muscles integer,
  variations_available integer,
  scraped_at timestamptz not null default now()
);

alter table public.exercises enable row level security;
""".strip()

FOODS_SQL = """
create extension if not exists pg_trgm;

create table if not exists public.foods (
  code text primary key,
  name text not null
);

create index if not exists foods_name_trgm_gist_idx
  on public.foods using gist (name gist_trgm_ops);

alter table public.foods enable row level security;

create or replace function public.search_food_names(
  search_text text,
  result_limit integer default 5
)
returns table (code text, name text, score real)
language sql
stable
security invoker
set search_path = public
as $$
  select
    foods.code,
    foods.name,
    (1 - (foods.name <-> trim(search_text)))::real as score
  from public.foods
  where length(trim(search_text)) >= 2
  order by foods.name <-> trim(search_text)
  limit least(greatest(result_limit, 1), 5);
$$;

notify pgrst, 'reload schema';
""".strip()

FOODS_SEARCH_OPTIMIZATION_SQL = """
set statement_timeout = 0;

create index if not exists foods_name_trgm_gist_idx
  on public.foods using gist (name gist_trgm_ops);

drop index if exists public.foods_name_trgm_idx;

create or replace function public.search_food_names(
  search_text text,
  result_limit integer default 5
)
returns table (code text, name text, score real)
language sql
stable
security invoker
set search_path = public
as $$
  select
    foods.code,
    foods.name,
    (1 - (foods.name <-> trim(search_text)))::real as score
  from public.foods
  where length(trim(search_text)) >= 2
  order by foods.name <-> trim(search_text)
  limit least(greatest(result_limit, 1), 5);
$$;

analyze public.foods;
notify pgrst, 'reload schema';
""".strip()

USERS_SQL = """
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text,
  profile_picture text,
  pace_gender text,
  goals text[] not null default '{}',
  workout_experience text,
  cuisine_preferences text[] not null default '{}',
  dietary_preferences text[] not null default '{}',
  preferred_units text not null default 'metric',
  bio text,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_username_format check (username ~ '^[a-z0-9_]{3,30}$'),
  constraint users_profile_picture_length check (profile_picture is null or length(profile_picture) <= 500),
  constraint users_pace_gender_check check (pace_gender is null or pace_gender in ('female', 'male')),
  constraint users_workout_experience_check check (workout_experience is null or workout_experience in ('beginner', 'intermediate', 'advanced')),
  constraint users_preferred_units_check check (preferred_units in ('metric', 'imperial')),
  constraint users_bio_length check (bio is null or length(bio) <= 500)
);

alter table public.users add column if not exists display_name text;
alter table public.users add column if not exists profile_picture text check (profile_picture is null or length(profile_picture) <= 500);
alter table public.users add column if not exists pace_gender text check (pace_gender is null or pace_gender in ('female', 'male'));
alter table public.users add column if not exists goals text[] not null default '{}';
alter table public.users add column if not exists workout_experience text check (workout_experience is null or workout_experience in ('beginner', 'intermediate', 'advanced'));
alter table public.users add column if not exists cuisine_preferences text[] not null default '{}';
alter table public.users add column if not exists dietary_preferences text[] not null default '{}';
alter table public.users add column if not exists preferred_units text not null default 'metric' check (preferred_units in ('metric', 'imperial'));
alter table public.users add column if not exists bio text check (bio is null or length(bio) <= 500);
alter table public.users add column if not exists onboarding_completed boolean not null default false;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('profile-pictures', 'profile-pictures', true, 1048576, array['image/png'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.users enable row level security;

revoke all on table public.users from anon;
grant select, update on table public.users to authenticated;
grant all on table public.users to service_role;

drop policy if exists "users_select_own_profile" on public.users;
create policy "users_select_own_profile"
  on public.users for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "users_update_own_profile" on public.users;
create policy "users_update_own_profile"
  on public.users for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_username text;
  requested_display_name text;
begin
  requested_username := lower(trim(new.raw_user_meta_data ->> 'username'));
  requested_display_name := nullif(trim(new.raw_user_meta_data ->> 'display_name'), '');
  if requested_username is null or requested_username !~ '^[a-z0-9_]{3,30}$' then
    raise exception 'invalid username';
  end if;

  insert into public.users (id, username, display_name)
  values (new.id, requested_username, requested_display_name)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

notify pgrst, 'reload schema';
""".strip()

BODY_METRICS_SQL = """
create table if not exists public.body_metrics (
  id integer primary key,
  name text not null unique,
  dimension text not null,
  category text not null,
  updated_at timestamptz not null default now(),
  constraint metrics_id_positive check (id > 0),
  constraint metrics_name_not_blank check (length(trim(name)) > 0),
  constraint metrics_dimension_not_blank check (length(trim(dimension)) > 0),
  constraint metrics_category_not_blank check (length(trim(category)) > 0)
);

create index if not exists metrics_category_idx on public.body_metrics (category);
create index if not exists metrics_dimension_idx on public.body_metrics (dimension);

alter table public.body_metrics enable row level security;

revoke all on table public.body_metrics from anon;
grant select on table public.body_metrics to authenticated;
grant all on table public.body_metrics to service_role;

drop policy if exists "metrics_read_authenticated" on public.body_metrics;
create policy "metrics_read_authenticated"
  on public.body_metrics for select
  to authenticated
  using (true);

notify pgrst, 'reload schema';
""".strip()

EXERCISE_METRICS_SQL = """
create table if not exists public.exercise_metrics (
  equipment text primary key,
  reps boolean not null,
  concentric_time boolean not null,
  eccentric_time boolean not null,
  isometric_time boolean not null,
  time boolean not null,
  set_rest_time boolean not null,
  exercise_rest_time boolean not null,
  sets boolean not null,
  weights boolean not null,
  band_color boolean not null,
  volume boolean not null,
  one_rep_max boolean not null,
  updated_at timestamptz not null default now(),
  constraint exercise_metrics_equipment_not_blank check (length(trim(equipment)) > 0)
);

alter table public.exercise_metrics enable row level security;

revoke all on table public.exercise_metrics from anon;
grant select on table public.exercise_metrics to authenticated;
grant all on table public.exercise_metrics to service_role;

drop policy if exists "exercise_metrics_read_authenticated" on public.exercise_metrics;
create policy "exercise_metrics_read_authenticated"
  on public.exercise_metrics for select
  to authenticated
  using (true);

notify pgrst, 'reload schema';
""".strip()

APP_SCHEMA_SQL = load_full_schema_sql()
AI_SESSIONS_SQL = load_ai_schema_sql()


def main() -> None:
    print(APP_SCHEMA_SQL)


if __name__ == "__main__":
    main()
