-- Additive Peak application schema.
-- This migration never removes existing tables and does not create the
-- full external food dataset. public.foods stores only code/name search rows;
-- detailed product data is resolved through the Open Food Facts API by code.

select pg_advisory_xact_lock(hashtextextended('peak_full_application_schema', 0));

create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text,
  profile_picture text,
  pace_gender text,
  goals text[] not null default '{}',
  workout_experience text,
  cuisine_preferences text[] not null default '{}',
  dietary_preferences text[] not null default '{}',
  preferred_units text not null default 'metric',
  bio text,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_username_format check (username ~ '^[a-z0-9_]{3,30}$'),
  constraint users_profile_picture_length check (profile_picture is null or length(profile_picture) <= 500),
  constraint users_pace_gender_check check (pace_gender is null or pace_gender in ('female', 'male')),
  constraint users_workout_experience_check check (workout_experience is null or workout_experience in ('beginner', 'intermediate', 'advanced')),
  constraint users_preferred_units_check check (preferred_units in ('metric', 'imperial')),
  constraint users_bio_length check (bio is null or length(bio) <= 500)
);

alter table public.users add column if not exists display_name text;
alter table public.users add column if not exists profile_picture text check (profile_picture is null or length(profile_picture) <= 500);
alter table public.users add column if not exists pace_gender text check (pace_gender is null or pace_gender in ('female', 'male'));
alter table public.users add column if not exists goals text[] not null default '{}';
alter table public.users add column if not exists workout_experience text check (workout_experience is null or workout_experience in ('beginner', 'intermediate', 'advanced'));
alter table public.users add column if not exists cuisine_preferences text[] not null default '{}';
alter table public.users add column if not exists dietary_preferences text[] not null default '{}';
alter table public.users add column if not exists preferred_units text not null default 'metric' check (preferred_units in ('metric', 'imperial'));
alter table public.users add column if not exists bio text check (bio is null or length(bio) <= 500);
alter table public.users add column if not exists onboarding_completed boolean not null default false;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('profile-pictures', 'profile-pictures', true, 1048576, array['image/png'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.exercise_metrics (
  equipment text primary key,
  reps boolean not null,
  concentric_time boolean not null,
  eccentric_time boolean not null,
  isometric_time boolean not null,
  time boolean not null,
  set_rest_time boolean not null,
  exercise_rest_time boolean not null,
  sets boolean not null,
  weights boolean not null,
  band_color boolean not null,
  volume boolean not null,
  one_rep_max boolean not null,
  updated_at timestamptz not null default now(),
  constraint exercise_metrics_equipment_not_blank check (length(trim(equipment)) > 0)
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null unique,
  force text,
  category text,
  mechanic text,
  equipment text,
  difficulty text,
  primary_muscle text,
  secondary_muscles integer,
  variations_available integer,
  scraped_at timestamptz not null default now()
);

alter table public.exercises add column if not exists force text;
alter table public.exercises add column if not exists category text;
alter table public.exercises add column if not exists mechanic text;
alter table public.exercises add column if not exists equipment text;
alter table public.exercises add column if not exists difficulty text;
alter table public.exercises add column if not exists primary_muscle text;
alter table public.exercises add column if not exists secondary_muscles integer;
alter table public.exercises add column if not exists variations_available integer;
alter table public.exercises add column if not exists scraped_at timestamptz default now();

create table if not exists public.foods (
  code text primary key,
  name text not null
);

alter table public.foods add column if not exists name text;

create index if not exists foods_name_trgm_gist_idx
  on public.foods using gist (name gist_trgm_ops);

create or replace function public.search_food_names(
  search_text text,
  result_limit integer default 5
)
returns table (code text, name text, score real)
language sql
stable
security invoker
set search_path = public
as $$
  select
    foods.code,
    foods.name,
    (1 - (foods.name <-> trim(search_text)))::real as score
  from public.foods
  where length(trim(search_text)) >= 2
  order by foods.name <-> trim(search_text)
  limit least(greatest(result_limit, 1), 5);
$$;

create table if not exists public.body_metrics (
  id integer primary key,
  name text not null unique,
  dimension text not null,
  category text not null,
  updated_at timestamptz not null default now(),
  constraint body_metrics_id_positive check (id > 0),
  constraint body_metrics_name_not_blank check (length(trim(name)) > 0)
);

create index if not exists metrics_category_idx on public.body_metrics (category);
create index if not exists metrics_dimension_idx on public.body_metrics (dimension);

create table if not exists public.muscle_groups (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.nutrients (
  id integer generated by default as identity primary key,
  key text not null unique,
  name text not null,
  canonical_unit text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nutrients_key_format check (key ~ '^[a-z][a-z0-9_]*$'),
  constraint nutrients_unit_not_blank check (length(trim(canonical_unit)) > 0)
);

create table if not exists public.exercise_muscle_groups (
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  muscle_group_id integer not null references public.muscle_groups(id) on delete restrict,
  role text not null check (role in ('primary', 'secondary')),
  primary key (exercise_id, muscle_group_id, role)
);

create index if not exists exercise_muscle_groups_muscle_idx
  on public.exercise_muscle_groups (muscle_group_id, role);

create table if not exists public.user_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  log_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, log_date),
  unique (id, user_id)
);

create table if not exists public.day_muscle_targets (
  day_id bigint not null,
  user_id uuid not null,
  muscle_group_id integer not null references public.muscle_groups(id) on delete restrict,
  primary key (day_id, muscle_group_id),
  foreign key (day_id, user_id)
    references public.user_days(id, user_id) on delete cascade
);

create index if not exists day_muscle_targets_user_day_idx
  on public.day_muscle_targets (user_id, day_id);

create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  day_id bigint not null,
  kind text not null check (kind in ('breakfast', 'lunch', 'dinner', 'additional')),
  meal_number integer not null default 0 check (meal_number >= 0),
  label text,
  created_at timestamptz not null default now(),
  unique (day_id, kind, meal_number),
  unique (id, user_id),
  foreign key (day_id, user_id)
    references public.user_days(id, user_id) on delete cascade,
  constraint meals_number_matches_kind check (
    (kind = 'additional' and meal_number >= 1)
    or (kind <> 'additional' and meal_number = 0)
  )
);

create table if not exists public.meal_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  meal_id bigint not null,
  food_code text not null references public.foods(code) on delete restrict,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null check (length(trim(unit)) > 0),
  consumed_grams numeric(14,4) check (consumed_grams is null or consumed_grams > 0),
  created_at timestamptz not null default now(),
  unique (id, user_id),
  foreign key (meal_id, user_id)
    references public.meals(id, user_id) on delete cascade
);

create index if not exists meal_items_meal_idx on public.meal_items (meal_id);
create index if not exists meal_items_food_code_idx on public.meal_items (food_code);

create table if not exists public.meal_nutrients (
  meal_item_id bigint not null,
  user_id uuid not null,
  nutrient_id integer not null references public.nutrients(id) on delete restrict,
  amount numeric(18,6) not null check (amount >= 0),
  source text not null check (length(trim(source)) > 0),
  captured_at timestamptz not null default now(),
  primary key (meal_item_id, nutrient_id),
  foreign key (meal_item_id, user_id)
    references public.meal_items(id, user_id) on delete cascade
);

create index if not exists meal_nutrients_user_nutrient_idx
  on public.meal_nutrients (user_id, nutrient_id);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  day_id bigint not null,
  started_at timestamptz,
  ended_at timestamptz,
  unique (id, user_id),
  foreign key (day_id, user_id)
    references public.user_days(id, user_id) on delete cascade,
  constraint workout_session_time_order check (
    ended_at is null or started_at is null or ended_at >= started_at
  )
);

create index if not exists workout_sessions_user_started_idx
  on public.workout_sessions (user_id, started_at);

create table if not exists public.workout_exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  session_id bigint not null,
  exercise_id bigint not null references public.exercises(id) on delete restrict,
  position integer not null check (position >= 1),
  equipment text not null references public.exercise_metrics(equipment) on delete restrict,
  exercise_rest_seconds numeric(10,3) check (
    exercise_rest_seconds is null or exercise_rest_seconds >= 0
  ),
  notes text,
  unique (id, user_id),
  unique (session_id, position),
  foreign key (session_id, user_id)
    references public.workout_sessions(id, user_id) on delete cascade
);

create index if not exists workout_exercises_exercise_idx
  on public.workout_exercises (exercise_id);

create table if not exists public.exercise_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  workout_exercise_id bigint not null,
  set_number integer not null check (set_number >= 1),
  reps integer check (reps is null or reps >= 0),
  weight numeric(12,4) check (weight is null or weight >= 0),
  concentric_seconds numeric(10,3) check (concentric_seconds is null or concentric_seconds >= 0),
  eccentric_seconds numeric(10,3) check (eccentric_seconds is null or eccentric_seconds >= 0),
  isometric_seconds numeric(10,3) check (isometric_seconds is null or isometric_seconds >= 0),
  duration_seconds numeric(12,3) check (duration_seconds is null or duration_seconds >= 0),
  rest_after_seconds numeric(10,3) check (rest_after_seconds is null or rest_after_seconds >= 0),
  band_color text,
  unique (workout_exercise_id, set_number),
  foreign key (workout_exercise_id, user_id)
    references public.workout_exercises(id, user_id) on delete cascade
);

create index if not exists exercise_sets_user_exercise_idx
  on public.exercise_sets (user_id, workout_exercise_id);

create table if not exists public.body_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  day_id bigint not null,
  body_metric_id integer not null references public.body_metrics(id) on delete restrict,
  value numeric(18,6) not null,
  unit text not null check (length(trim(unit)) > 0),
  measured_at timestamptz not null,
  notes text,
  foreign key (day_id, user_id)
    references public.user_days(id, user_id) on delete cascade
);

create index if not exists body_measurements_user_metric_time_idx
  on public.body_measurements (user_id, body_metric_id, measured_at);

create table if not exists public.friendships (
  user_a_id uuid not null references public.users(id) on delete cascade,
  user_b_id uuid not null references public.users(id) on delete cascade,
  requested_by uuid not null references public.users(id) on delete cascade,
  status_changed_by uuid references public.users(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'blocked', 'removed')),
  requested_at timestamptz not null default now(),
  responded_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_a_id, user_b_id),
  constraint friendships_canonical_pair check (user_a_id < user_b_id),
  constraint friendships_requester_is_participant check (
    requested_by in (user_a_id, user_b_id)
  ),
  constraint friendships_actor_is_participant check (
    status_changed_by is null or status_changed_by in (user_a_id, user_b_id)
  )
);

create index if not exists friendships_user_b_idx on public.friendships (user_b_id, status);

create table if not exists public.leagues (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.users(id) on delete cascade,
  name varchar(100) not null check (length(trim(name)) > 0),
  description text,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  timezone varchar(50) not null,
  status text not null default 'draft'
    check (status in ('draft', 'active', 'completed', 'cancelled')),
  scoring_mode text not null default 'equal'
    check (scoring_mode in ('equal', 'weighted')),
  missing_data_policy text not null default 'disqualify'
    check (missing_data_policy in ('disqualify', 'zero_score')),
  show_raw_values boolean not null default false,
  created_at timestamptz not null default now(),
  finalized_at timestamptz,
  constraint leagues_time_order check (ends_at > starts_at)
);

create index if not exists leagues_owner_idx on public.leagues (owner_id, status);

create table if not exists public.league_members (
  league_id bigint not null references public.leagues(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  invited_by uuid not null references public.users(id) on delete restrict,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  status text not null default 'invited'
    check (status in ('invited', 'accepted', 'declined', 'removed')),
  invited_at timestamptz not null default now(),
  responded_at timestamptz,
  joined_at timestamptz,
  primary key (league_id, user_id)
);

create index if not exists league_members_user_status_idx
  on public.league_members (user_id, status);

create table if not exists public.league_metrics (
  id bigint generated by default as identity primary key,
  league_id bigint not null references public.leagues(id) on delete cascade,
  metric_type text not null check (metric_type in ('body', 'nutrient', 'exercise')),
  body_metric_id integer references public.body_metrics(id) on delete restrict,
  nutrient_id integer references public.nutrients(id) on delete restrict,
  exercise_id bigint references public.exercises(id) on delete restrict,
  exercise_measure text check (exercise_measure in (
    'reps', 'weight', 'concentric_seconds', 'eccentric_seconds',
    'isometric_seconds', 'duration_seconds', 'rest_after_seconds',
    'sets', 'volume', 'one_rep_max'
  )),
  value_method text not null check (value_method in (
    'sum', 'average', 'maximum', 'minimum', 'latest', 'change', 'percent_change'
  )),
  direction text not null default 'higher'
    check (direction in ('higher', 'lower', 'closest_to_target')),
  weight numeric(10,4) not null default 1 check (weight > 0),
  target_value numeric(18,6),
  minimum_observations integer not null default 1 check (minimum_observations >= 1),
  created_at timestamptz not null default now(),
  unique (league_id, id),
  constraint league_metrics_source_matches_type check (
    (metric_type = 'body' and body_metric_id is not null and nutrient_id is null
      and exercise_id is null and exercise_measure is null)
    or
    (metric_type = 'nutrient' and nutrient_id is not null and body_metric_id is null
      and exercise_id is null and exercise_measure is null)
    or
    (metric_type = 'exercise' and exercise_measure is not null
      and body_metric_id is null and nutrient_id is null)
  ),
  constraint league_metrics_target_required check (
    direction <> 'closest_to_target' or target_value is not null
  )
);

create table if not exists public.league_metric_results (
  league_metric_id bigint not null,
  league_id bigint not null,
  user_id uuid not null,
  baseline_value numeric(18,6),
  result_value numeric(18,6),
  observations integer not null default 0 check (observations >= 0),
  normalized_score numeric(10,6),
  weighted_score numeric(10,6),
  metric_rank integer check (metric_rank is null or metric_rank >= 1),
  finalized_at timestamptz not null,
  primary key (league_metric_id, user_id),
  foreign key (league_id, league_metric_id)
    references public.league_metrics(league_id, id) on delete cascade,
  foreign key (league_id, user_id)
    references public.league_members(league_id, user_id) on delete cascade
);

create index if not exists league_metric_results_league_user_idx
  on public.league_metric_results (league_id, user_id);

create table if not exists public.league_results (
  league_id bigint not null,
  user_id uuid not null,
  total_score numeric(10,6) not null,
  final_rank integer not null check (final_rank >= 1),
  finalized_at timestamptz not null,
  primary key (league_id, user_id),
  foreign key (league_id, user_id)
    references public.league_members(league_id, user_id) on delete cascade
);

create index if not exists league_results_rank_idx
  on public.league_results (league_id, final_rank);

create or replace view public.user_days_with_weekday
with (security_invoker = true)
as
select
  id,
  user_id,
  log_date,
  extract(isodow from log_date)::smallint as weekday_iso,
  trim(to_char(log_date, 'Day')) as weekday,
  created_at
from public.user_days;

create or replace view public.nutrient_intake_facts
with (security_invoker = true)
as
select
  ud.user_id,
  ud.log_date,
  extract(isodow from ud.log_date)::smallint as weekday_iso,
  m.id as meal_id,
  m.kind as meal_kind,
  m.meal_number,
  mi.id as meal_item_id,
  mi.food_code,
  f.name as food_name,
  n.id as nutrient_id,
  n.key as nutrient_key,
  n.name as nutrient_name,
  mn.amount,
  n.canonical_unit,
  mn.source
from public.meal_nutrients mn
join public.meal_items mi on mi.id = mn.meal_item_id and mi.user_id = mn.user_id
join public.meals m on m.id = mi.meal_id and m.user_id = mi.user_id
join public.user_days ud on ud.id = m.day_id and ud.user_id = m.user_id
join public.foods f on f.code = mi.food_code
join public.nutrients n on n.id = mn.nutrient_id;

comment on table public.exercise_metrics is
  'Equipment capability matrix controlling which typed exercise-set metrics are applicable.';
comment on column public.nutrients.key is
  'Stable machine-readable nutrient identifier, for example vitamin_b12; not an authentication key.';
comment on column public.meal_nutrients.meal_item_id is
  'Exact consumed food item described by this nutrient snapshot.';
comment on column public.meal_nutrients.source is
  'Data provenance such as open_food_facts, nutrition_label, manual, or calculated.';
comment on column public.workout_exercises.position is
  'One-based exercise order within the workout session.';
comment on column public.workout_exercises.notes is
  'Optional comments for this exercise occurrence in this workout.';
comment on table public.exercise_sets is
  'One completed set. Applicable nullable metric columns are selected through workout_exercises.equipment and exercise_metrics.';

-- Add the catalog capability relationship to an existing exercises table
-- without rejecting legacy rows. New and updated rows are still checked.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.exercises'::regclass
      and conname = 'exercises_equipment_fkey'
  ) then
    alter table public.exercises
      add constraint exercises_equipment_fkey
      foreign key (equipment) references public.exercise_metrics(equipment)
      on delete restrict not valid;
  end if;
end;
$$;

insert into public.muscle_groups (name) values
  ('Abdominals'), ('Abductors'), ('Adductors'), ('Biceps'), ('Calves'),
  ('Chest'), ('Forearms'), ('Glutes'), ('Hamstrings'), ('Lats'),
  ('Lower Back'), ('Middle Back'), ('Neck'), ('Quadriceps'), ('Shoulders'),
  ('Traps'), ('Triceps')
on conflict (name) do nothing;

insert into public.nutrients (key, name, canonical_unit) values
  ('energy_kcal', 'Energy', 'kcal'),
  ('fat', 'Fat', 'g'),
  ('saturated_fat', 'Saturated Fat', 'g'),
  ('trans_fat', 'Trans Fat', 'g'),
  ('carbohydrate', 'Carbohydrate', 'g'),
  ('fibre', 'Fibre', 'g'),
  ('sugars', 'Sugars', 'g'),
  ('protein', 'Protein', 'g'),
  ('cholesterol', 'Cholesterol', 'mg'),
  ('sodium', 'Sodium', 'mg'),
  ('potassium', 'Potassium', 'mg'),
  ('calcium', 'Calcium', 'mg'),
  ('iron', 'Iron', 'mg'),
  ('vitamin_a', 'Vitamin A', 'ug'),
  ('vitamin_c', 'Vitamin C', 'mg'),
  ('vitamin_d', 'Vitamin D', 'ug'),
  ('vitamin_e', 'Vitamin E', 'mg'),
  ('vitamin_k', 'Vitamin K', 'ug'),
  ('vitamin_b1', 'Thiamine (Vitamin B1)', 'mg'),
  ('vitamin_b2', 'Riboflavin (Vitamin B2)', 'mg'),
  ('niacin', 'Niacin', 'mg'),
  ('vitamin_b6', 'Vitamin B6', 'mg'),
  ('folate', 'Folate', 'ug'),
  ('vitamin_b12', 'Vitamin B12', 'ug'),
  ('choline', 'Choline', 'mg'),
  ('biotin', 'Biotin', 'ug'),
  ('pantothenic_acid', 'Pantothenic Acid', 'mg'),
  ('phosphorus', 'Phosphorus', 'mg'),
  ('iodine', 'Iodine', 'ug'),
  ('magnesium', 'Magnesium', 'mg'),
  ('zinc', 'Zinc', 'mg'),
  ('selenium', 'Selenium', 'ug'),
  ('copper', 'Copper', 'mg'),
  ('manganese', 'Manganese', 'mg'),
  ('chromium', 'Chromium', 'ug'),
  ('molybdenum', 'Molybdenum', 'ug'),
  ('chloride', 'Chloride', 'mg')
on conflict (key) do update
set name = excluded.name,
    canonical_unit = excluded.canonical_unit,
    updated_at = now();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_username text;
  requested_display_name text;
begin
  requested_username := lower(trim(new.raw_user_meta_data ->> 'username'));
  requested_display_name := nullif(trim(new.raw_user_meta_data ->> 'display_name'), '');
  if requested_username is null or requested_username !~ '^[a-z0-9_]{3,30}$' then
    raise exception 'invalid username';
  end if;

  insert into public.users (id, username, display_name)
  values (new.id, requested_username, requested_display_name)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
  before update on public.users
  for each row execute procedure public.set_updated_at();

drop trigger if exists nutrients_set_updated_at on public.nutrients;
create trigger nutrients_set_updated_at
  before update on public.nutrients
  for each row execute procedure public.set_updated_at();

drop trigger if exists friendships_set_updated_at on public.friendships;
create trigger friendships_set_updated_at
  before update on public.friendships
  for each row execute procedure public.set_updated_at();

create or replace function public.is_league_member(target_league_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.league_members
    where league_id = target_league_id
      and user_id = (select auth.uid())
      and status = 'accepted'
  );
$$;

create or replace function public.is_league_admin(target_league_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.leagues
    where id = target_league_id and owner_id = (select auth.uid())
  ) or exists (
    select 1 from public.league_members
    where league_id = target_league_id
      and user_id = (select auth.uid())
      and status = 'accepted'
      and role in ('owner', 'admin')
  );
$$;

revoke all on function public.set_updated_at() from public;
revoke all on function public.handle_new_user() from public;
revoke all on function public.search_food_names(text, integer) from public;
revoke all on function public.is_league_member(bigint) from public;
revoke all on function public.is_league_admin(bigint) from public;
grant execute on function public.is_league_member(bigint) to authenticated, service_role;
grant execute on function public.is_league_admin(bigint) to authenticated, service_role;
grant execute on function public.search_food_names(text, integer) to authenticated, service_role;

-- Enable RLS everywhere exposed through the public schema.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users', 'exercise_metrics', 'exercises', 'exercise_muscle_groups',
    'foods', 'body_metrics', 'muscle_groups', 'nutrients', 'user_days',
    'day_muscle_targets', 'meals', 'meal_items', 'meal_nutrients',
    'workout_sessions', 'workout_exercises', 'exercise_sets',
    'body_measurements', 'friendships', 'leagues', 'league_members',
    'league_metrics', 'league_metric_results', 'league_results'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon', table_name);
    execute format('grant all on table public.%I to service_role', table_name);
  end loop;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'exercise_metrics', 'exercises', 'exercise_muscle_groups', 'foods',
    'body_metrics', 'muscle_groups', 'nutrients'
  ] loop
    execute format('grant select on table public.%I to authenticated', table_name);
    execute format('drop policy if exists reference_read_authenticated on public.%I', table_name);
    execute format(
      'create policy reference_read_authenticated on public.%I for select to authenticated using (true)',
      table_name
    );
  end loop;
end;
$$;

grant select, update on table public.users to authenticated;
drop policy if exists users_select_own_profile on public.users;
create policy users_select_own_profile
  on public.users for select to authenticated
  using ((select auth.uid()) = id);
drop policy if exists users_update_own_profile on public.users;
create policy users_update_own_profile
  on public.users for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'user_days', 'day_muscle_targets', 'meals', 'meal_items',
    'meal_nutrients', 'workout_sessions', 'workout_exercises',
    'exercise_sets', 'body_measurements'
  ] loop
    execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
    execute format('drop policy if exists owner_all on public.%I', table_name);
    execute format(
      'create policy owner_all on public.%I for all to authenticated '
      'using ((select auth.uid()) = user_id) '
      'with check ((select auth.uid()) = user_id)',
      table_name
    );
  end loop;
end;
$$;

grant select, insert on table public.friendships to authenticated;
revoke update, delete on table public.friendships from authenticated;
drop policy if exists friendships_participant_read on public.friendships;
create policy friendships_participant_read
  on public.friendships for select to authenticated
  using ((select auth.uid()) in (user_a_id, user_b_id));
drop policy if exists friendships_request on public.friendships;
create policy friendships_request
  on public.friendships for insert to authenticated
  with check (
    requested_by = (select auth.uid())
    and (select auth.uid()) in (user_a_id, user_b_id)
    and status = 'pending'
  );
drop policy if exists friendships_participant_update on public.friendships;

grant select, insert, update, delete on table public.leagues to authenticated;
drop policy if exists leagues_member_read on public.leagues;
create policy leagues_member_read
  on public.leagues for select to authenticated
  using (owner_id = (select auth.uid()) or public.is_league_member(id));
drop policy if exists leagues_owner_insert on public.leagues;
create policy leagues_owner_insert
  on public.leagues for insert to authenticated
  with check (owner_id = (select auth.uid()));
drop policy if exists leagues_owner_update on public.leagues;
create policy leagues_owner_update
  on public.leagues for update to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));
drop policy if exists leagues_owner_delete on public.leagues;
create policy leagues_owner_delete
  on public.leagues for delete to authenticated
  using (owner_id = (select auth.uid()));

grant select, insert, update, delete on table public.league_members to authenticated;
drop policy if exists league_members_member_read on public.league_members;
create policy league_members_member_read
  on public.league_members for select to authenticated
  using (
    user_id = (select auth.uid())
    or public.is_league_member(league_id)
    or public.is_league_admin(league_id)
  );
drop policy if exists league_members_admin_write on public.league_members;
create policy league_members_admin_write
  on public.league_members for all to authenticated
  using (public.is_league_admin(league_id))
  with check (public.is_league_admin(league_id));

grant select, insert, update, delete on table public.league_metrics to authenticated;
drop policy if exists league_metrics_member_read on public.league_metrics;
create policy league_metrics_member_read
  on public.league_metrics for select to authenticated
  using (public.is_league_member(league_id) or public.is_league_admin(league_id));
drop policy if exists league_metrics_admin_write on public.league_metrics;
create policy league_metrics_admin_write
  on public.league_metrics for all to authenticated
  using (public.is_league_admin(league_id))
  with check (public.is_league_admin(league_id));

grant select on table public.league_metric_results, public.league_results to authenticated;
drop policy if exists league_metric_results_member_read on public.league_metric_results;
create policy league_metric_results_member_read
  on public.league_metric_results for select to authenticated
  using (public.is_league_member(league_id) or public.is_league_admin(league_id));
drop policy if exists league_results_member_read on public.league_results;
create policy league_results_member_read
  on public.league_results for select to authenticated
  using (public.is_league_member(league_id) or public.is_league_admin(league_id));

grant select on table public.user_days_with_weekday, public.nutrient_intake_facts to authenticated;

grant usage, select on all sequences in schema public to authenticated, service_role;

notify pgrst, 'reload schema';
